# Generated by Django 5.1.4 on 2024-12-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='contact',
            name='supject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
